const comments = [
    
    {
        "name": "Greg Geller",
        "comment": " ",
        "itinerary": "Exciting time travel back to the German Democratic Republic.",
        "itineraryDesc": "The Wall and barbed wire shielded the GDR from the outside world. But what was everyday life like under socialism? Discover Berlin's largest and most diverse exhibition on the subject with more than 35 thematic areas and an original furnished tower block apartment! ​​​Under the scientific direction of the renowned historian Dr. Stefan Wolle we resurrect the past for you.",
        "image": "4.jpg",
        "imgItinerary": "berlintour.jpg",
        "Policy": "Free cancellation: Cancel up to 24 hours in advance to receive a full refund.",
        "price": 5,
        "likes": 0,
        "duration": "3 hours",
        "hashtags": ["#berlin ", "#germany ", "#history ", "#wall"],
        
    },
    {
        "name": "Susan Brie",
        "comment": " ",
        "itinerary": "Explore Berlin's art scene on this guided walking tour. ",
        "itineraryDesc": "Join this guided walking tour to discover Berlin's thriving art scene. Visit contemporary art galleries and learn about the hottest artists in town. The art galleries are selected exclusively by the editorial staff of ART magazine each month, covering everything from paintings to sculptures.",
        "image": "5.jpg",
        "imgItinerary": "berlinmuseum.jpg",
        "Policy": "No refunds.",
        "price": 3,
        "likes": 0,
        "duration": "5 hours",
        "hashtags": ["#berlin ", "#germany ", "#art ", "#museum"],
    },
    {
        "name": "John Doe",
        "comment": " ",
        "itinerary": "Bora Bora Jet Ski Tour, Lunch at Bloody Mary's & Eco Shark / Ray Snorkel Cruise",
        "itineraryDesc": "Get out on the water at Bora Bora om this combo Jet Ski and snorkeling tour that includes a shark and stingray boat safari. Select a single or double Jet Ski and zip around the Polynesian paradise with an experienced guide. After lunch at Bloody Mary’s, hop in a powerboat to a shallow lagoon for a close encounter with black-tip reef sharks and stingrays.",
        "image": "6.jpg",
        "imgItinerary": "boraborajet.jpg",
        "Policy": "Hotel pickup offered.",
        "price": 4,
        "likes": 0,
        "duration": "6 hours",
        "hashtags": ["#borabora ", "#jetski ", "#sharks ", "#snorkeling"],
    },
    {
        "name": "Alice Simpson",
        "comment": " ",
        "itinerary": "Full Day Lagoon Group Tour in Bora Bora with Lunch",
        "itineraryDesc": "The whole family will enjoy this day trip on the lagoon in Bora Bora, soaking up the sights and experiences. Don a snorkeling mask and fins and start your exploration in the shallow waters, looking at the colorful tropical fish, coral, and stingrays. Graduate to the open ocean and keep an eye out for different types of shark. Refresh after this adventure with a buffet lunch of local dishes will be served on the beach.",
        "image": "7.jpg",
        "imgItinerary": "boraborasnorkel.jpg",
        "Policy": "Free cancellation: Cancel up to 48 hours in advance to receive a full refund.",
        "price": 5,
        "likes": 0,
        "duration": "5 hours",
        "hashtags": ["#fish ", "#snorkel ", "#coral ", "#borabora"],
    },
    {
        "name": "Margot Robertson",
        "comment": " ",
        "itinerary": "Caminito's Tour in Buenos Aires.",
        "itineraryDesc": "This guided walking tour to visit one of the most picturesque neighborhoods of the city, with a walk through the colorful sites of Caminito and La Boca, and enjoy the most varied options that are made in each place you visit. Discover this mythical and famous neighborhood.",
        "image": "9.jpg",
        "imgItinerary": "bsasitinerario2.jpg",
        "Policy": "Free cancellation: Cancel up to 48 hours in advance to receive a full refund.",
        "price": 2,
        "likes": 0,
        "duration": "6 hours",
        "hashtags": ["#caminito ", "#boca ", "#tango ", "#colourfull"],
    },
    {
        "name": "Robert Jonhson",
        "comment": " ",
        "itinerary": "Museum Tour.",
        "itineraryDesc": "Discover how Buenos Aires earned its nickname, Paris of the South, as your art historian guide takes you on a private 7-hour tour of the city's most important museums and art galleries. Art lovers will be in their element as they check out highlights like the Museo Arte Moderno, MALBA, the Museo de Bellas Artes, or the Amalia Lacroze de Fortabat Art Collection, then discover notable local artists at some of Recoleta's most exclusive art galleries.",
        "image": "2.jpg",
        "imgItinerary": "bsasitinerario1.jpg",
        "Policy": "No refunds.",
        "price": 5,
        "likes": 0,
        "duration": "7 hours",
        "hashtags": ["#malba ", "#palermo ", "#recoleta ", "#art"],
        "city" : 
    },
    
]

export default comments;